import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/templates/layout/navbar/Navbar";
import Footer from "@/app/components/templates/layout/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${inter.className} flex min-h-screen  flex-col items-center justify-between bg-Light-Blue `}>
        <Navbar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
