import "./styles/globals.css";
import Navbar from "@/app/components/templates/layout/navbar/Navbar";
import { dana, morabba } from "@/app/styles/fonts"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${dana.variable, morabba.variable}  bg-Light-Blue flex flex-col-reverse tablet:flex-col justify-between min-h-screen `}>
        <Navbar />
        <div className="container">
          {children}
        </div>

      </body>
    </html>
  );
}
