import "./styles/globals.css";
import { dana, morabba } from "@/app/styles/fonts"
import Header from "@/app/components/templates/layout/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${dana.variable, morabba.variable}   bg-Light-Blue flex flex-col-reverse md:flex-col justify-between min-h-screen `}>
        <Header />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
